// @ts-check
// The docs sidebar. Autogenerated from the docs/ folder; each doc's order comes
// from its `sidebar_position` frontmatter.

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [{ type: 'autogenerated', dirName: '.' }],
};

module.exports = sidebars;
